[package]
name = "rust"
version = "0.1.0"
authors = ["Caleb Eby <caleb.eby01@gmail.com>"]
edition = "2018"

[[bin]]
name = "train"
path = "src/train.rs"

[lib]
crate-type = ["cdylib"]

[features]
serialize = []

[dependencies]
wasm-bindgen = "0.2.79"
wee_alloc = "0.4.5"
getrandom = { version = "0.2.6", features = ["js"] }
ndarray = "0.15.4"
serde_json = "1.0.81"
neuronika = {version = "0.2.0", features = ["serialize"]}
serde = {version = "1.0.137", features = ["derive"]}
rand = "0.8.5"

[dependencies.web-sys]
version = "0.3.4"
features = [
  'console',
  'CanvasRenderingContext2d',
  'Document',
  'Element',
  'EventTarget',
  'HtmlCanvasElement',
  'HtmlDivElement',
  'HtmlButtonElement',
  'HtmlElement',
  'MouseEvent',
  'Node',
  'Window',
]

