name: Node.js CI
on: [push, pull_request]

jobs:
  test:
    name: Test Rust
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo test --manifest-path rust/Cargo.toml
